//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.05 at 07:50:13 AM VET 
//


package com.banesco.xmlns.applicationservice.portalpaymentriskratingoutappsvc;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.banesco.xmlns.applicationservice.portalpaymentriskratingoutappsvc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.banesco.xmlns.applicationservice.portalpaymentriskratingoutappsvc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ValidateCustomerBlackListRq }
     * 
     */
    public ValidateCustomerBlackListRq createValidateCustomerBlackListRq() {
        return new ValidateCustomerBlackListRq();
    }

    /**
     * Create an instance of {@link ValidateCustomerBlackListRs }
     * 
     */
    public ValidateCustomerBlackListRs createValidateCustomerBlackListRs() {
        return new ValidateCustomerBlackListRs();
    }

    /**
     * Create an instance of {@link ValidateCustomerBlackListRs.BlackList }
     * 
     */
    public ValidateCustomerBlackListRs.BlackList createValidateCustomerBlackListRsBlackList() {
        return new ValidateCustomerBlackListRs.BlackList();
    }

    /**
     * Create an instance of {@link ValidateCustomerBlackListRq.Customer }
     * 
     */
    public ValidateCustomerBlackListRq.Customer createValidateCustomerBlackListRqCustomer() {
        return new ValidateCustomerBlackListRq.Customer();
    }

    /**
     * Create an instance of {@link ValidateCustomerBlackListRq.Customer.PersonInfo }
     * 
     */
    public ValidateCustomerBlackListRq.Customer.PersonInfo createValidateCustomerBlackListRqCustomerPersonInfo() {
        return new ValidateCustomerBlackListRq.Customer.PersonInfo();
    }

    /**
     * Create an instance of {@link ValidateCustomerBlackListRs.BlackList.BlackListRec }
     * 
     */
    public ValidateCustomerBlackListRs.BlackList.BlackListRec createValidateCustomerBlackListRsBlackListBlackListRec() {
        return new ValidateCustomerBlackListRs.BlackList.BlackListRec();
    }

    /**
     * Create an instance of {@link ValidateCustomerBlackListRq.Customer.PersonInfo.OtherIdentDoc }
     * 
     */
    public ValidateCustomerBlackListRq.Customer.PersonInfo.OtherIdentDoc createValidateCustomerBlackListRqCustomerPersonInfoOtherIdentDoc() {
        return new ValidateCustomerBlackListRq.Customer.PersonInfo.OtherIdentDoc();
    }

}
