//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.05 at 07:50:13 AM VET 
//


package com.banesco.xmlns.applicationservice.portalpaymentriskratingoutappsvc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.banesco.xmlns.enterpriseobjects.msgrshdr.MsgRsHdr;
import com.banesco.xmlns.enterpriseobjects.status.Status;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MsgRsHdr" type="{http://xmlns.banesco.com/EnterpriseObjects/MsgRsHdr}MsgRsHdr" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Status" type="{http://xmlns.banesco.com/EnterpriseObjects/Status}Status" minOccurs="0"/&gt;
 *         &lt;element name="BlackList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="BlackListRec" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="BlackListBanesco" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="BlackListCbn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msgRsHdr",
    "status",
    "blackList"
})
@XmlRootElement(name = "validateCustomerBlackList_Rs")
public class ValidateCustomerBlackListRs {

    @XmlElement(name = "MsgRsHdr")
    protected List<MsgRsHdr> msgRsHdr;
    @XmlElement(name = "Status")
    protected Status status;
    @XmlElement(name = "BlackList")
    protected ValidateCustomerBlackListRs.BlackList blackList;

    /**
     * Gets the value of the msgRsHdr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the msgRsHdr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMsgRsHdr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MsgRsHdr }
     * 
     * 
     */
    public List<MsgRsHdr> getMsgRsHdr() {
        if (msgRsHdr == null) {
            msgRsHdr = new ArrayList<MsgRsHdr>();
        }
        return this.msgRsHdr;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the blackList property.
     * 
     * @return
     *     possible object is
     *     {@link ValidateCustomerBlackListRs.BlackList }
     *     
     */
    public ValidateCustomerBlackListRs.BlackList getBlackList() {
        return blackList;
    }

    /**
     * Sets the value of the blackList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidateCustomerBlackListRs.BlackList }
     *     
     */
    public void setBlackList(ValidateCustomerBlackListRs.BlackList value) {
        this.blackList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="BlackListRec" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="BlackListBanesco" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="BlackListCbn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "blackListRec"
    })
    public static class BlackList {

        @XmlElement(name = "BlackListRec")
        protected ValidateCustomerBlackListRs.BlackList.BlackListRec blackListRec;

        /**
         * Gets the value of the blackListRec property.
         * 
         * @return
         *     possible object is
         *     {@link ValidateCustomerBlackListRs.BlackList.BlackListRec }
         *     
         */
        public ValidateCustomerBlackListRs.BlackList.BlackListRec getBlackListRec() {
            return blackListRec;
        }

        /**
         * Sets the value of the blackListRec property.
         * 
         * @param value
         *     allowed object is
         *     {@link ValidateCustomerBlackListRs.BlackList.BlackListRec }
         *     
         */
        public void setBlackListRec(ValidateCustomerBlackListRs.BlackList.BlackListRec value) {
            this.blackListRec = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="BlackListBanesco" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="BlackListCbn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "blackListBanesco",
            "blackListCbn"
        })
        public static class BlackListRec {

            @XmlElement(name = "BlackListBanesco")
            protected String blackListBanesco;
            @XmlElement(name = "BlackListCbn")
            protected String blackListCbn;

            /**
             * Gets the value of the blackListBanesco property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBlackListBanesco() {
                return blackListBanesco;
            }

            /**
             * Sets the value of the blackListBanesco property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBlackListBanesco(String value) {
                this.blackListBanesco = value;
            }

            /**
             * Gets the value of the blackListCbn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBlackListCbn() {
                return blackListCbn;
            }

            /**
             * Sets the value of the blackListCbn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBlackListCbn(String value) {
                this.blackListCbn = value;
            }

        }

    }

}
