//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.03 at 11:13:06 AM VET 
//


package com.banesco.xmlns.enterpriseobjects.bill;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.banesco.xmlns.enterpriseobjects.organization.Organization;


/**
 * <p>Java class for AllianceBilling complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AllianceBilling"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AgreeNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CompanySvc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PhonePlan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Organization" type="{http://xmlns.banesco.com/EnterpriseObjects/Organization}Organization" minOccurs="0"/&gt;
 *         &lt;element name="Intermediary" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="GenericValue" type="{http://xmlns.banesco.com/EnterpriseObjects/Bill}GenericValue" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="DigitAgreeNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AllianceBilling", propOrder = {
    "agreeNum",
    "companySvc",
    "phonePlan",
    "organization",
    "intermediary",
    "genericValue",
    "digitAgreeNum"
})
public class AllianceBilling {

    @XmlElement(name = "AgreeNum")
    protected String agreeNum;
    @XmlElement(name = "CompanySvc")
    protected String companySvc;
    @XmlElement(name = "PhonePlan")
    protected String phonePlan;
    @XmlElement(name = "Organization")
    protected Organization organization;
    @XmlElement(name = "Intermediary")
    protected String intermediary;
    @XmlElement(name = "GenericValue")
    protected List<GenericValue> genericValue;
    @XmlElement(name = "DigitAgreeNum")
    protected String digitAgreeNum;

    /**
     * Gets the value of the agreeNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreeNum() {
        return agreeNum;
    }

    /**
     * Sets the value of the agreeNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreeNum(String value) {
        this.agreeNum = value;
    }

    /**
     * Gets the value of the companySvc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanySvc() {
        return companySvc;
    }

    /**
     * Sets the value of the companySvc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanySvc(String value) {
        this.companySvc = value;
    }

    /**
     * Gets the value of the phonePlan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhonePlan() {
        return phonePlan;
    }

    /**
     * Sets the value of the phonePlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhonePlan(String value) {
        this.phonePlan = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    public Organization getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    public void setOrganization(Organization value) {
        this.organization = value;
    }

    /**
     * Gets the value of the intermediary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntermediary() {
        return intermediary;
    }

    /**
     * Sets the value of the intermediary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermediary(String value) {
        this.intermediary = value;
    }

    /**
     * Gets the value of the genericValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the genericValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGenericValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenericValue }
     * 
     * 
     */
    public List<GenericValue> getGenericValue() {
        if (genericValue == null) {
            genericValue = new ArrayList<GenericValue>();
        }
        return this.genericValue;
    }

    /**
     * Gets the value of the digitAgreeNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigitAgreeNum() {
        return digitAgreeNum;
    }

    /**
     * Sets the value of the digitAgreeNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigitAgreeNum(String value) {
        this.digitAgreeNum = value;
    }

}
