//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.03 at 11:13:06 AM VET 
//


package com.banesco.xmlns.enterpriseobjects.bill;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.banesco.xmlns.enterpriseobjects.account.Account;
import com.banesco.xmlns.enterpriseobjects.customer.Customer;
import com.banesco.xmlns.enterpriseobjects.service.Service;


/**
 * <p>Java class for Bill complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bill"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AllianceBilling" type="{http://xmlns.banesco.com/EnterpriseObjects/Bill}AllianceBilling" minOccurs="0"/&gt;
 *         &lt;element name="BillId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillInfo" type="{http://xmlns.banesco.com/EnterpriseObjects/Bill}BillInfo" minOccurs="0"/&gt;
 *         &lt;element name="BillStatus" type="{http://xmlns.banesco.com/EnterpriseObjects/Bill}BillStatus" minOccurs="0"/&gt;
 *         &lt;element name="Customer" type="{http://xmlns.banesco.com/EnterpriseObjects/Customer}Customer" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="GenericValue" type="{http://xmlns.banesco.com/EnterpriseObjects/Bill}GenericValue" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="BillInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PhoneNum" type="{http://xmlns.banesco.com/EnterpriseObjects/Bill}PhoneNum" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Account" type="{http://xmlns.banesco.com/EnterpriseObjects/Account}Account" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Service" type="{http://xmlns.banesco.com/EnterpriseObjects/Service}Service" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="PaymentInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ApprovalNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bill", propOrder = {
    "allianceBilling",
    "billId",
    "billInfo",
    "billStatus",
    "customer",
    "genericValue",
    "billInd",
    "phoneNum",
    "account",
    "service",
    "paymentInd",
    "approvalNumber"
})
public class Bill {

    @XmlElement(name = "AllianceBilling")
    protected AllianceBilling allianceBilling;
    @XmlElement(name = "BillId")
    protected String billId;
    @XmlElement(name = "BillInfo")
    protected BillInfo billInfo;
    @XmlElement(name = "BillStatus")
    protected BillStatus billStatus;
    @XmlElement(name = "Customer")
    protected List<Customer> customer;
    @XmlElement(name = "GenericValue")
    protected List<GenericValue> genericValue;
    @XmlElement(name = "BillInd")
    protected String billInd;
    @XmlElement(name = "PhoneNum")
    protected List<PhoneNum> phoneNum;
    @XmlElement(name = "Account")
    protected List<Account> account;
    @XmlElement(name = "Service")
    protected List<Service> service;
    @XmlElement(name = "PaymentInd")
    protected String paymentInd;
    @XmlElement(name = "ApprovalNumber")
    protected String approvalNumber;

    /**
     * Gets the value of the allianceBilling property.
     * 
     * @return
     *     possible object is
     *     {@link AllianceBilling }
     *     
     */
    public AllianceBilling getAllianceBilling() {
        return allianceBilling;
    }

    /**
     * Sets the value of the allianceBilling property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllianceBilling }
     *     
     */
    public void setAllianceBilling(AllianceBilling value) {
        this.allianceBilling = value;
    }

    /**
     * Gets the value of the billId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillId() {
        return billId;
    }

    /**
     * Sets the value of the billId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillId(String value) {
        this.billId = value;
    }

    /**
     * Gets the value of the billInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BillInfo }
     *     
     */
    public BillInfo getBillInfo() {
        return billInfo;
    }

    /**
     * Sets the value of the billInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillInfo }
     *     
     */
    public void setBillInfo(BillInfo value) {
        this.billInfo = value;
    }

    /**
     * Gets the value of the billStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BillStatus }
     *     
     */
    public BillStatus getBillStatus() {
        return billStatus;
    }

    /**
     * Sets the value of the billStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillStatus }
     *     
     */
    public void setBillStatus(BillStatus value) {
        this.billStatus = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Customer }
     * 
     * 
     */
    public List<Customer> getCustomer() {
        if (customer == null) {
            customer = new ArrayList<Customer>();
        }
        return this.customer;
    }

    /**
     * Gets the value of the genericValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the genericValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGenericValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenericValue }
     * 
     * 
     */
    public List<GenericValue> getGenericValue() {
        if (genericValue == null) {
            genericValue = new ArrayList<GenericValue>();
        }
        return this.genericValue;
    }

    /**
     * Gets the value of the billInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillInd() {
        return billInd;
    }

    /**
     * Sets the value of the billInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillInd(String value) {
        this.billInd = value;
    }

    /**
     * Gets the value of the phoneNum property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the phoneNum property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhoneNum().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhoneNum }
     * 
     * 
     */
    public List<PhoneNum> getPhoneNum() {
        if (phoneNum == null) {
            phoneNum = new ArrayList<PhoneNum>();
        }
        return this.phoneNum;
    }

    /**
     * Gets the value of the account property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the account property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Account }
     * 
     * 
     */
    public List<Account> getAccount() {
        if (account == null) {
            account = new ArrayList<Account>();
        }
        return this.account;
    }

    /**
     * Gets the value of the service property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the service property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Service }
     * 
     * 
     */
    public List<Service> getService() {
        if (service == null) {
            service = new ArrayList<Service>();
        }
        return this.service;
    }

    /**
     * Gets the value of the paymentInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentInd() {
        return paymentInd;
    }

    /**
     * Sets the value of the paymentInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentInd(String value) {
        this.paymentInd = value;
    }

    /**
     * Gets the value of the approvalNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovalNumber() {
        return approvalNumber;
    }

    /**
     * Sets the value of the approvalNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovalNumber(String value) {
        this.approvalNumber = value;
    }

}
