//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.03 at 11:13:06 AM VET 
//


package com.banesco.xmlns.enterpriseobjects.bill;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BillDt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DueDt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillSummAmt" type="{http://xmlns.banesco.com/EnterpriseObjects/Bill}BillSummAmt" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="LastBillSummAmt" type="{http://xmlns.banesco.com/EnterpriseObjects/Bill}LastBillSummAmt" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="FormRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BillSummAmtId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillInfo", propOrder = {
    "billDt",
    "dueDt",
    "billSummAmt",
    "lastBillSummAmt",
    "formRef",
    "billSummAmtId"
})
public class BillInfo {

    @XmlElement(name = "BillDt")
    protected String billDt;
    @XmlElement(name = "DueDt")
    protected String dueDt;
    @XmlElement(name = "BillSummAmt")
    protected List<BillSummAmt> billSummAmt;
    @XmlElement(name = "LastBillSummAmt")
    protected List<LastBillSummAmt> lastBillSummAmt;
    @XmlElement(name = "FormRef")
    protected String formRef;
    @XmlElement(name = "BillSummAmtId")
    protected String billSummAmtId;

    /**
     * Gets the value of the billDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillDt() {
        return billDt;
    }

    /**
     * Sets the value of the billDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillDt(String value) {
        this.billDt = value;
    }

    /**
     * Gets the value of the dueDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueDt() {
        return dueDt;
    }

    /**
     * Sets the value of the dueDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueDt(String value) {
        this.dueDt = value;
    }

    /**
     * Gets the value of the billSummAmt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the billSummAmt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBillSummAmt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BillSummAmt }
     * 
     * 
     */
    public List<BillSummAmt> getBillSummAmt() {
        if (billSummAmt == null) {
            billSummAmt = new ArrayList<BillSummAmt>();
        }
        return this.billSummAmt;
    }

    /**
     * Gets the value of the lastBillSummAmt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lastBillSummAmt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLastBillSummAmt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LastBillSummAmt }
     * 
     * 
     */
    public List<LastBillSummAmt> getLastBillSummAmt() {
        if (lastBillSummAmt == null) {
            lastBillSummAmt = new ArrayList<LastBillSummAmt>();
        }
        return this.lastBillSummAmt;
    }

    /**
     * Gets the value of the formRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormRef() {
        return formRef;
    }

    /**
     * Sets the value of the formRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormRef(String value) {
        this.formRef = value;
    }

    /**
     * Gets the value of the billSummAmtId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillSummAmtId() {
        return billSummAmtId;
    }

    /**
     * Sets the value of the billSummAmtId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillSummAmtId(String value) {
        this.billSummAmtId = value;
    }

}
