//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.03 at 11:13:06 AM VET 
//


package com.banesco.xmlns.enterpriseobjects.bill;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.banesco.xmlns.enterpriseobjects.bill package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.banesco.xmlns.enterpriseobjects.bill
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Bill }
     * 
     */
    public Bill createBill() {
        return new Bill();
    }

    /**
     * Create an instance of {@link AllianceBilling }
     * 
     */
    public AllianceBilling createAllianceBilling() {
        return new AllianceBilling();
    }

    /**
     * Create an instance of {@link BillStatus }
     * 
     */
    public BillStatus createBillStatus() {
        return new BillStatus();
    }

    /**
     * Create an instance of {@link BillInfo }
     * 
     */
    public BillInfo createBillInfo() {
        return new BillInfo();
    }

    /**
     * Create an instance of {@link BillSummAmt }
     * 
     */
    public BillSummAmt createBillSummAmt() {
        return new BillSummAmt();
    }

    /**
     * Create an instance of {@link CurAmt }
     * 
     */
    public CurAmt createCurAmt() {
        return new CurAmt();
    }

    /**
     * Create an instance of {@link LastBillSummAmt }
     * 
     */
    public LastBillSummAmt createLastBillSummAmt() {
        return new LastBillSummAmt();
    }

    /**
     * Create an instance of {@link GenericValue }
     * 
     */
    public GenericValue createGenericValue() {
        return new GenericValue();
    }

    /**
     * Create an instance of {@link PhoneNum }
     * 
     */
    public PhoneNum createPhoneNum() {
        return new PhoneNum();
    }

}
