//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.03 at 11:13:06 AM VET 
//


package com.banesco.xmlns.applicationservice.bnetcreditcardoutappsvc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.banesco.xmlns.enterpriseobjects.account.Account;
import com.banesco.xmlns.enterpriseobjects.account.SvcAcctStatus;
import com.banesco.xmlns.enterpriseobjects.msgrqhdr.MsgRqHdr;
import com.banesco.xmlns.enterpriseobjects.selrangedt.SelRangeDt;


/**
 * <p>Java class for readCreditCardTransactions_Rq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="readCreditCardTransactions_Rq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MsgRqHdr" type="{http://xmlns.banesco.com/EnterpriseObjects/MsgRqHdr}MsgRqHdr"/&gt;
 *         &lt;element name="Account" type="{http://xmlns.banesco.com/EnterpriseObjects/Account}Account" minOccurs="0"/&gt;
 *         &lt;element name="SelRangeDt" type="{http://xmlns.banesco.com/EnterpriseObjects/SelRangeDt}SelRangeDt" minOccurs="0"/&gt;
 *         &lt;element name="SvcAcctStatus" type="{http://xmlns.banesco.com/EnterpriseObjects/Account}SvcAcctStatus" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "readCreditCardTransactions_Rq", propOrder = {
    "msgRqHdr",
    "account",
    "selRangeDt",
    "svcAcctStatus"
})
public class ReadCreditCardTransactionsRq {

    @XmlElement(name = "MsgRqHdr", required = true)
    protected MsgRqHdr msgRqHdr;
    @XmlElement(name = "Account")
    protected Account account;
    @XmlElement(name = "SelRangeDt")
    protected SelRangeDt selRangeDt;
    @XmlElement(name = "SvcAcctStatus")
    protected SvcAcctStatus svcAcctStatus;

    /**
     * Gets the value of the msgRqHdr property.
     * 
     * @return
     *     possible object is
     *     {@link MsgRqHdr }
     *     
     */
    public MsgRqHdr getMsgRqHdr() {
        return msgRqHdr;
    }

    /**
     * Sets the value of the msgRqHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgRqHdr }
     *     
     */
    public void setMsgRqHdr(MsgRqHdr value) {
        this.msgRqHdr = value;
    }

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link Account }
     *     
     */
    public Account getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link Account }
     *     
     */
    public void setAccount(Account value) {
        this.account = value;
    }

    /**
     * Gets the value of the selRangeDt property.
     * 
     * @return
     *     possible object is
     *     {@link SelRangeDt }
     *     
     */
    public SelRangeDt getSelRangeDt() {
        return selRangeDt;
    }

    /**
     * Sets the value of the selRangeDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelRangeDt }
     *     
     */
    public void setSelRangeDt(SelRangeDt value) {
        this.selRangeDt = value;
    }

    /**
     * Gets the value of the svcAcctStatus property.
     * 
     * @return
     *     possible object is
     *     {@link SvcAcctStatus }
     *     
     */
    public SvcAcctStatus getSvcAcctStatus() {
        return svcAcctStatus;
    }

    /**
     * Sets the value of the svcAcctStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SvcAcctStatus }
     *     
     */
    public void setSvcAcctStatus(SvcAcctStatus value) {
        this.svcAcctStatus = value;
    }

}
