//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.06 at 12:58:04 PM COT 
//


package com.banesco.xmlns.applicationservice.apifinancialaccountoutappsvc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.banesco.xmlns.applicationservice.apifinancialaccountoutappsvc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReadAccountBalanceRq_QNAME = new QName("http://xmlns.banesco.com/ApplicationService/APIFinancialAccountOutAppSvc/", "readAccountBalance_Rq");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.banesco.xmlns.applicationservice.apifinancialaccountoutappsvc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReadAccountBalanceRq }
     * 
     */
    public ReadAccountBalanceRq createReadAccountBalanceRq() {
        return new ReadAccountBalanceRq();
    }

    @XmlElementDecl(namespace = "http://xmlns.banesco.com/ApplicationService/APIFinancialAccountOutAppSvc/", name = "readAccountBalance_Rq")
    public JAXBElement<ReadAccountBalanceRq> createReadAccountBalanceRq(ReadAccountBalanceRq value) {
        return new JAXBElement<ReadAccountBalanceRq>(_ReadAccountBalanceRq_QNAME, ReadAccountBalanceRq.class, null, value);
    }


    /**
     * Create an instance of {@link ReadAccountBalanceRs }
     * 
     */
    public ReadAccountBalanceRs createReadAccountBalanceRs() {
        return new ReadAccountBalanceRs();
    }

    /**
     * Create an instance of {@link TransferBanescoAccountRq }
     * 
     */
    public TransferBanescoAccountRq createTransferBanescoAccountRq() {
        return new TransferBanescoAccountRq();
    }

    /**
     * Create an instance of {@link TransferBanescoAccountRs }
     * 
     */
    public TransferBanescoAccountRs createTransferBanescoAccountRs() {
        return new TransferBanescoAccountRs();
    }

    /**
     * Create an instance of {@link TransferBanescoAccountRs.Taxes }
     * 
     */
    public TransferBanescoAccountRs.Taxes createTransferBanescoAccountRsTaxes() {
        return new TransferBanescoAccountRs.Taxes();
    }

    /**
     * Create an instance of {@link TransferBanescoAccountRs.Taxes.TaxInfo }
     * 
     */
    public TransferBanescoAccountRs.Taxes.TaxInfo createTransferBanescoAccountRsTaxesTaxInfo() {
        return new TransferBanescoAccountRs.Taxes.TaxInfo();
    }

    /**
     * Create an instance of {@link TransferBanescoAccountRs.Customer }
     * 
     */
    public TransferBanescoAccountRs.Customer createTransferBanescoAccountRsCustomer() {
        return new TransferBanescoAccountRs.Customer();
    }

    /**
     * Create an instance of {@link TransferBanescoAccountRq.Banking }
     * 
     */
    public TransferBanescoAccountRq.Banking createTransferBanescoAccountRqBanking() {
        return new TransferBanescoAccountRq.Banking();
    }

    /**
     * Create an instance of {@link TransferBanescoAccountRq.Banking.BankAcctTrnRec }
     * 
     */
    public TransferBanescoAccountRq.Banking.BankAcctTrnRec createTransferBanescoAccountRqBankingBankAcctTrnRec() {
        return new TransferBanescoAccountRq.Banking.BankAcctTrnRec();
    }

    /**
     * Create an instance of {@link TransferBanescoAccountRq.Account }
     * 
     */
    public TransferBanescoAccountRq.Account createTransferBanescoAccountRqAccount() {
        return new TransferBanescoAccountRq.Account();
    }

    /**
     * Create an instance of {@link ReadAccountBalanceRs.Customer }
     * 
     */
    public ReadAccountBalanceRs.Customer createReadAccountBalanceRsCustomer() {
        return new ReadAccountBalanceRs.Customer();
    }

    /**
     * Create an instance of {@link ReadAccountBalanceRs.Account }
     * 
     */
    public ReadAccountBalanceRs.Account createReadAccountBalanceRsAccount() {
        return new ReadAccountBalanceRs.Account();
    }

    /**
     * Create an instance of {@link ReadAccountBalanceRs.Account.AcctBal }
     * 
     */
    public ReadAccountBalanceRs.Account.AcctBal createReadAccountBalanceRsAccountAcctBal() {
        return new ReadAccountBalanceRs.Account.AcctBal();
    }

    /**
     * Create an instance of {@link ReadAccountBalanceRq.Account }
     * 
     */
    public ReadAccountBalanceRq.Account createReadAccountBalanceRqAccount() {
        return new ReadAccountBalanceRq.Account();
    }

    /**
     * Create an instance of {@link TransferBanescoAccountRs.Taxes.TaxInfo.CurAmt }
     * 
     */
    public TransferBanescoAccountRs.Taxes.TaxInfo.CurAmt createTransferBanescoAccountRsTaxesTaxInfoCurAmt() {
        return new TransferBanescoAccountRs.Taxes.TaxInfo.CurAmt();
    }

    /**
     * Create an instance of {@link TransferBanescoAccountRs.Customer.PersonInfo }
     * 
     */
    public TransferBanescoAccountRs.Customer.PersonInfo createTransferBanescoAccountRsCustomerPersonInfo() {
        return new TransferBanescoAccountRs.Customer.PersonInfo();
    }

    /**
     * Create an instance of {@link TransferBanescoAccountRq.Banking.BankAcctTrnRec.CurAmt }
     * 
     */
    public TransferBanescoAccountRq.Banking.BankAcctTrnRec.CurAmt createTransferBanescoAccountRqBankingBankAcctTrnRecCurAmt() {
        return new TransferBanescoAccountRq.Banking.BankAcctTrnRec.CurAmt();
    }

    /**
     * Create an instance of {@link TransferBanescoAccountRq.Account.BankInfo }
     * 
     */
    public TransferBanescoAccountRq.Account.BankInfo createTransferBanescoAccountRqAccountBankInfo() {
        return new TransferBanescoAccountRq.Account.BankInfo();
    }

    /**
     * Create an instance of {@link ReadAccountBalanceRs.Customer.PersonInfo }
     * 
     */
    public ReadAccountBalanceRs.Customer.PersonInfo createReadAccountBalanceRsCustomerPersonInfo() {
        return new ReadAccountBalanceRs.Customer.PersonInfo();
    }

    /**XmlElementDecl
     * Create an instance of {@link ReadAccountBalanceRs.Account.AcctBal.CurAmt }
     * 
     */
    public ReadAccountBalanceRs.Account.AcctBal.CurAmt createReadAccountBalanceRsAccountAcctBalCurAmt() {
        return new ReadAccountBalanceRs.Account.AcctBal.CurAmt();
    }

}
