//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.10 at 06:04:40 PM VET 
//


package com.banesco.xmlns.enterpriseobjects.msgrqhdr;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.banesco.xmlns.enterpriseobjects.msgrqhdr package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.banesco.xmlns.enterpriseobjects.msgrqhdr
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MsgRqHdr }
     * 
     */
    public MsgRqHdr createMsgRqHdr() {
        return new MsgRqHdr();
    }

    /**
     * Create an instance of {@link NetworkTrnInfo }
     * 
     */
    public NetworkTrnInfo createNetworkTrnInfo() {
        return new NetworkTrnInfo();
    }

    /**
     * Create an instance of {@link ApplicantData }
     * 
     */
    public ApplicantData createApplicantData() {
        return new ApplicantData();
    }

    /**
     * Create an instance of {@link RecCtrlIn }
     * 
     */
    public RecCtrlIn createRecCtrlIn() {
        return new RecCtrlIn();
    }

    /**
     * Create an instance of {@link VBProtocol }
     * 
     */
    public VBProtocol createVBProtocol() {
        return new VBProtocol();
    }

}
